// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v5.29.3
// source: proto/witwiz.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerInput_Action int32

const (
	PlayerInput_MOVE_UP    PlayerInput_Action = 0
	PlayerInput_MOVE_RIGHT PlayerInput_Action = 1
	PlayerInput_MOVE_DOWN  PlayerInput_Action = 2
	PlayerInput_MOVE_LEFT  PlayerInput_Action = 3
	PlayerInput_SHOOT      PlayerInput_Action = 4
)

// Enum value maps for PlayerInput_Action.
var (
	PlayerInput_Action_name = map[int32]string{
		0: "MOVE_UP",
		1: "MOVE_RIGHT",
		2: "MOVE_DOWN",
		3: "MOVE_LEFT",
		4: "SHOOT",
	}
	PlayerInput_Action_value = map[string]int32{
		"MOVE_UP":    0,
		"MOVE_RIGHT": 1,
		"MOVE_DOWN":  2,
		"MOVE_LEFT":  3,
		"SHOOT":      4,
	}
)

func (x PlayerInput_Action) Enum() *PlayerInput_Action {
	p := new(PlayerInput_Action)
	*p = x
	return p
}

func (x PlayerInput_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerInput_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_witwiz_proto_enumTypes[0].Descriptor()
}

func (PlayerInput_Action) Type() protoreflect.EnumType {
	return &file_proto_witwiz_proto_enumTypes[0]
}

func (x PlayerInput_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerInput_Action.Descriptor instead.
func (PlayerInput_Action) EnumDescriptor() ([]byte, []int) {
	return file_proto_witwiz_proto_rawDescGZIP(), []int{0, 0}
}

type PlayerInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId int32              `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Action   PlayerInput_Action `protobuf:"varint,2,opt,name=action,proto3,enum=witwiz.PlayerInput_Action" json:"action,omitempty"`
}

func (x *PlayerInput) Reset() {
	*x = PlayerInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_witwiz_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInput) ProtoMessage() {}

func (x *PlayerInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_witwiz_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInput.ProtoReflect.Descriptor instead.
func (*PlayerInput) Descriptor() ([]byte, []int) {
	return file_proto_witwiz_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerInput) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerInput) GetAction() PlayerInput_Action {
	if x != nil {
		return x.Action
	}
	return PlayerInput_MOVE_UP
}

type GameStateUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Players     []*PlayerState     `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	Projectiles []*ProjectileState `protobuf:"bytes,2,rep,name=projectiles,proto3" json:"projectiles,omitempty"`
}

func (x *GameStateUpdate) Reset() {
	*x = GameStateUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_witwiz_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameStateUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStateUpdate) ProtoMessage() {}

func (x *GameStateUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_witwiz_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStateUpdate.ProtoReflect.Descriptor instead.
func (*GameStateUpdate) Descriptor() ([]byte, []int) {
	return file_proto_witwiz_proto_rawDescGZIP(), []int{1}
}

func (x *GameStateUpdate) GetPlayers() []*PlayerState {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *GameStateUpdate) GetProjectiles() []*ProjectileState {
	if x != nil {
		return x.Projectiles
	}
	return nil
}

type PlayerState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId          int32   `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PositionX         float32 `protobuf:"fixed32,2,opt,name=position_x,json=positionX,proto3" json:"position_x,omitempty"`
	PositionY         float32 `protobuf:"fixed32,3,opt,name=position_y,json=positionY,proto3" json:"position_y,omitempty"`
	BoundingBoxWidth  float32 `protobuf:"fixed32,4,opt,name=bounding_box_width,json=boundingBoxWidth,proto3" json:"bounding_box_width,omitempty"`
	BoundingBoxHeight float32 `protobuf:"fixed32,5,opt,name=bounding_box_height,json=boundingBoxHeight,proto3" json:"bounding_box_height,omitempty"`
}

func (x *PlayerState) Reset() {
	*x = PlayerState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_witwiz_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerState) ProtoMessage() {}

func (x *PlayerState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_witwiz_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerState.ProtoReflect.Descriptor instead.
func (*PlayerState) Descriptor() ([]byte, []int) {
	return file_proto_witwiz_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerState) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerState) GetPositionX() float32 {
	if x != nil {
		return x.PositionX
	}
	return 0
}

func (x *PlayerState) GetPositionY() float32 {
	if x != nil {
		return x.PositionY
	}
	return 0
}

func (x *PlayerState) GetBoundingBoxWidth() float32 {
	if x != nil {
		return x.BoundingBoxWidth
	}
	return 0
}

func (x *PlayerState) GetBoundingBoxHeight() float32 {
	if x != nil {
		return x.BoundingBoxHeight
	}
	return 0
}

type ProjectileState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectileId      int32   `protobuf:"varint,1,opt,name=projectile_id,json=projectileId,proto3" json:"projectile_id,omitempty"`
	OwnerId           int32   `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	PositionX         float32 `protobuf:"fixed32,3,opt,name=position_x,json=positionX,proto3" json:"position_x,omitempty"`
	PositionY         float32 `protobuf:"fixed32,4,opt,name=position_y,json=positionY,proto3" json:"position_y,omitempty"`
	BoundingBoxWidth  float32 `protobuf:"fixed32,5,opt,name=bounding_box_width,json=boundingBoxWidth,proto3" json:"bounding_box_width,omitempty"`
	BoundingBoxHeight float32 `protobuf:"fixed32,6,opt,name=bounding_box_height,json=boundingBoxHeight,proto3" json:"bounding_box_height,omitempty"`
	VelocityX         float32 `protobuf:"fixed32,7,opt,name=velocity_x,json=velocityX,proto3" json:"velocity_x,omitempty"`
	VelocityY         float32 `protobuf:"fixed32,8,opt,name=velocity_y,json=velocityY,proto3" json:"velocity_y,omitempty"`
}

func (x *ProjectileState) Reset() {
	*x = ProjectileState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_witwiz_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectileState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectileState) ProtoMessage() {}

func (x *ProjectileState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_witwiz_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectileState.ProtoReflect.Descriptor instead.
func (*ProjectileState) Descriptor() ([]byte, []int) {
	return file_proto_witwiz_proto_rawDescGZIP(), []int{3}
}

func (x *ProjectileState) GetProjectileId() int32 {
	if x != nil {
		return x.ProjectileId
	}
	return 0
}

func (x *ProjectileState) GetOwnerId() int32 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *ProjectileState) GetPositionX() float32 {
	if x != nil {
		return x.PositionX
	}
	return 0
}

func (x *ProjectileState) GetPositionY() float32 {
	if x != nil {
		return x.PositionY
	}
	return 0
}

func (x *ProjectileState) GetBoundingBoxWidth() float32 {
	if x != nil {
		return x.BoundingBoxWidth
	}
	return 0
}

func (x *ProjectileState) GetBoundingBoxHeight() float32 {
	if x != nil {
		return x.BoundingBoxHeight
	}
	return 0
}

func (x *ProjectileState) GetVelocityX() float32 {
	if x != nil {
		return x.VelocityX
	}
	return 0
}

func (x *ProjectileState) GetVelocityY() float32 {
	if x != nil {
		return x.VelocityY
	}
	return 0
}

var File_proto_witwiz_proto protoreflect.FileDescriptor

var file_proto_witwiz_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x69, 0x74, 0x77, 0x69, 0x7a, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x77, 0x69, 0x74, 0x77, 0x69, 0x7a, 0x22, 0xae, 0x01, 0x0a,
	0x0b, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x32, 0x0a, 0x06, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x77, 0x69, 0x74, 0x77,
	0x69, 0x7a, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x2e, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4e, 0x0a,
	0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0b, 0x0a, 0x07, 0x4d, 0x4f, 0x56, 0x45, 0x5f,
	0x55, 0x50, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x4d, 0x4f, 0x56, 0x45, 0x5f, 0x52, 0x49, 0x47,
	0x48, 0x54, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x4d, 0x4f, 0x56, 0x45, 0x5f, 0x44, 0x4f, 0x57,
	0x4e, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x4d, 0x4f, 0x56, 0x45, 0x5f, 0x4c, 0x45, 0x46, 0x54,
	0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x48, 0x4f, 0x4f, 0x54, 0x10, 0x04, 0x22, 0x7b, 0x0a,
	0x0f, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x12, 0x2d, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x77, 0x69, 0x74, 0x77, 0x69, 0x7a, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x12,
	0x39, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x77, 0x69, 0x74, 0x77, 0x69, 0x7a, 0x2e, 0x50, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x0b, 0x70,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6c, 0x65, 0x73, 0x22, 0xc6, 0x01, 0x0a, 0x0b, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x58, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x59, 0x12, 0x2c, 0x0a, 0x12, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x5f, 0x62, 0x6f, 0x78, 0x5f, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x10, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x42, 0x6f, 0x78, 0x57, 0x69,
	0x64, 0x74, 0x68, 0x12, 0x2e, 0x0a, 0x13, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x5f,
	0x62, 0x6f, 0x78, 0x5f, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x11, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x42, 0x6f, 0x78, 0x48, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x22, 0xab, 0x02, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69,
	0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x69, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c,
	0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08,
	0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x58, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x59, 0x12, 0x2c, 0x0a, 0x12, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x5f, 0x62, 0x6f, 0x78, 0x5f, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x10, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x42, 0x6f, 0x78, 0x57, 0x69,
	0x64, 0x74, 0x68, 0x12, 0x2e, 0x0a, 0x13, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x5f,
	0x62, 0x6f, 0x78, 0x5f, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x11, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x42, 0x6f, 0x78, 0x48, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79, 0x5f,
	0x78, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x76, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74,
	0x79, 0x58, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79, 0x5f, 0x79,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x76, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79,
	0x59, 0x32, 0x48, 0x0a, 0x06, 0x57, 0x69, 0x74, 0x57, 0x69, 0x7a, 0x12, 0x3e, 0x0a, 0x08, 0x4a,
	0x6f, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x13, 0x2e, 0x77, 0x69, 0x74, 0x77, 0x69, 0x7a,
	0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x17, 0x2e, 0x77,
	0x69, 0x74, 0x77, 0x69, 0x7a, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x0e, 0x5a, 0x0c, 0x77,
	0x69, 0x74, 0x77, 0x69, 0x7a, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_witwiz_proto_rawDescOnce sync.Once
	file_proto_witwiz_proto_rawDescData = file_proto_witwiz_proto_rawDesc
)

func file_proto_witwiz_proto_rawDescGZIP() []byte {
	file_proto_witwiz_proto_rawDescOnce.Do(func() {
		file_proto_witwiz_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_witwiz_proto_rawDescData)
	})
	return file_proto_witwiz_proto_rawDescData
}

var file_proto_witwiz_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_witwiz_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_witwiz_proto_goTypes = []interface{}{
	(PlayerInput_Action)(0), // 0: witwiz.PlayerInput.Action
	(*PlayerInput)(nil),     // 1: witwiz.PlayerInput
	(*GameStateUpdate)(nil), // 2: witwiz.GameStateUpdate
	(*PlayerState)(nil),     // 3: witwiz.PlayerState
	(*ProjectileState)(nil), // 4: witwiz.ProjectileState
}
var file_proto_witwiz_proto_depIdxs = []int32{
	0, // 0: witwiz.PlayerInput.action:type_name -> witwiz.PlayerInput.Action
	3, // 1: witwiz.GameStateUpdate.players:type_name -> witwiz.PlayerState
	4, // 2: witwiz.GameStateUpdate.projectiles:type_name -> witwiz.ProjectileState
	1, // 3: witwiz.WitWiz.JoinGame:input_type -> witwiz.PlayerInput
	2, // 4: witwiz.WitWiz.JoinGame:output_type -> witwiz.GameStateUpdate
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_witwiz_proto_init() }
func file_proto_witwiz_proto_init() {
	if File_proto_witwiz_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_witwiz_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_witwiz_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameStateUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_witwiz_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_witwiz_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectileState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_witwiz_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_witwiz_proto_goTypes,
		DependencyIndexes: file_proto_witwiz_proto_depIdxs,
		EnumInfos:         file_proto_witwiz_proto_enumTypes,
		MessageInfos:      file_proto_witwiz_proto_msgTypes,
	}.Build()
	File_proto_witwiz_proto = out.File
	file_proto_witwiz_proto_rawDesc = nil
	file_proto_witwiz_proto_goTypes = nil
	file_proto_witwiz_proto_depIdxs = nil
}
